# EMPTY.TCL - empty Tcl file used to create font cache.  
#
# Copyright 1998 Wind River Systems, Inc.
#
# modification history
# --------------------
# 01a,20sep98,bjl written.
#
# DESCRIPTION
# Before sourcing INSTW32.TCL, UITclSh is run with this file.  
# The purpose is to simply start UITclSh, which will then generate
# a font cache if necessary, and display the font cache creation process
# to the screen (see MWWRAPPER).  This is needed since MWWRAPPER will 
# otherwise suppress output.  
#
# */

